### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by arnaudbey** [elheloum/TEI2JSON#4]
Peut-être ajouter un readme.md à la racine du projet et mettre un peu de doc (qu'st ce que ça fait, comment s'en servir, la licence du logiciel, etc.
> voir https://www.makeareadme.com/

**Comment by elheloum** [comment]
Dites-nous si le README vous convient ou si c'est soft :) 
Merci

**Comment by elheloum** [comment]
+ est-ce que cela vous convient que ce soit en anglais ? ou vous préférez que ce soit en FR ?

**Comment by arnaudbey** [comment]
c'est bien que ce soir en anglais IMO. 
Moyen de mettre les commandes à lancer depuis un terminal classique pour lancer le script ?

**Comment by elheloum** [comment]
Le problème de la documentation est réglé.
Afin que ça fonctionne il faut bien installé le fichier requirements.txt (suivre les consignes du README.md)

Pouvez-vous me confirmer que ça fonctionne à partir de votre terminal svp ?

**Comment by elheloum** [comment]
@arnaudbey nous avons une sortie qui nous satisfait ! Serait-il possible de nous donner votre avis afin de résoudre les potentiels problèmes :) Merci d'avance
