### ISSUE TITLE
question :)

### ISSUE THREAD

**Issue by arnaudbey** [elheloum/TEI2JSON#5]
êtes vous sûrs d'avoir toutes les données en sortie ? J'ai essayé votre sortie et il n'y a pas d'enfants possible sur ```<p>```. Vu que c'est une balise un peu générique qui je pense peut contenir pas mal de chose, je suis sceptique. Soit c'est bien normal, vous partez d'un schéma assez restreint, soit vous récupérez pas tous les enfants possibles...

Bref, si vous avez moyen de vérifier, c'est cool.  ça va de pair avec #4 , ce qui me permettrait de me servir de votre code pour tester moi-même.

**Comment by elheloum** [comment]
Nous n'avons pas encore traité le cas où les enfants se trouvent dans les références "tei_macro" donc c'est normal que la balise <p> n'ait pas encore tous ses enfants. car si nous regardons dans le .rng elle a : <ref name="tei_macro.paraContent"/> qui lui va nous permettre de récupérer tous les enfants. C'est là où la récursivité rentre en jeux. On est dessus, c'est encore un peu bancale. Nous vous tenons au courant dès que c'est complètement fonctionnel :) 

En ce qui concerne la #4 , je rédige ça aujourd'hui et je le joins au projet. (Normalement dans notre planning c'était la dernière chose à faire mais nous pouvons avancé un peu dessus)

**Comment by elheloum** [comment]
@samiboucs a réussi a récupéré tous les enfants même pour la balise "p". J'ai déposé la nouvelle sortie .json ainsi que le nouveau code. N'hésitez pas à nous faire part de vos remarques sur les nouveaux fichiers
