### ISSUE TITLE
Documentation des éléments

### ISSUE THREAD

**Issue by elheloum** [elheloum/TEI2JSON#6]
Nous avons récupéré la documentation des éléments en français. Nous n'avons pas pu trouvé la totalité des doc en FR.
Je vous ai déposé la nouvelle version du .json 
Pourriez vous me dire si cela vous convient ou si vous souhaitez avoir les deux documentations (FR et EN)  pour chaque élément ?

**Comment by arnaudbey** [comment]
bonjour,
pour info les issues github sont généralement utilisées pour lister les bugs éventuels ou des suggestions d'amélioration/de fonctionnalités ;)
